server:
  port: 8081
spring:
  datasource:
    #mysql 配置
    dbType: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.208.47:3306/meishikecan?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Huang123
    # 驱动配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息:初始化大小，最小，最大
    initialSize: 1
    minIdle: 1
    maxActive: 3
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #验证库是否正常sql
    validationQuery: select 'x'
    #空闲时验证，防止连接断开
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 120.77.208.47
    port: 6379
    password: Huang123
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  rabbitmq:
    host: 120.77.208.47
    port: 5672
    username: rabbitmq
    password: Huang123
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
  data:
    elasticsearch:
      cluster-name: my-elastic
      cluster-nodes: 120.77.208.47:9300
      repositories:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bin.meishikecan.entity
  config-location: classpath:framework/mybatis-config.xml
logging:
  config: classpath:framework/log4j2-config.xml
  level:
    cn.jay.repository: trace

